version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 portbackend.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - media_volume:/app/media
      - sqlite_volume:/app/db_data
    env_file:
      - .env

volumes:
  media_volume:
  sqlite_volume:
